.TH  rssgen  1 " 2016/11/23"
.SS NAME
.P
rssgen - generate rss from a list of html documents.

.SS DESCRIPTION
.P
rssgen reads html documents and produces an rss feed that describes those documents. It gathers data in the following manner:
.P
Document title is read from the "title" meta tag. If that\(aqs not present it\(aqs read from the "h1" header of the document. If that\(aqs not present the file name is used.
.P
Document description is read from the "description" meta tag. if that\(aqs not present it\(aqs read from the "h2" header.
.P
Document author is read from the "author" meta tag.
.P
Publication date is read from the non-standard "pubDate" meta tag. If that\(aqs not present then the file modification time is used.

.SS DISCLAIMER
.P
This is free software. It comes with no guarentees and I take no responsiblity if it makes your computer explode or opens a portal to the demon dimensions, or does anything.

.SS INSTALL
.P
After unpacking the tarball do the usual "./configure; make; make install"
.P
    cd rssgen-1.0
    ./configure
    make
    make install

.SS SYNTAX
.P
	rssgen <base url> -b [ -o <path> ] [ -t <title> ] [ -s <self url> ] [ -x <exclude pattern> ] <input file>
.P

.TP
\fB<base url>\fP
The path that the items in the rss file will appear at. So, if building an rss for files under "http://myblog.com/blogposts/" the base url is "http://myblog.com/blogposts/"
.TP
\fB-b\fP
Strip any leading path off input file names
.TP
\fB-o <path>\fP
Path to RSS output file. Defaults to "./feed.rss"
.TP
\fB-t <title>\fP
Title of RSS Channel.
.TP
\fB-s <self url>\fP
Optional "self" url for this RSS Channel.
.TP
\fB-x <exclude pattern>\fP
Don\(aqt include files matching this pattern.
.P
The first argument to rssgen must be the base URL where the documents will be stored. Thus this command
.nf

	rssgen http://mysite.org/blog/ \-t "My Blog" post1.html post2.html
.fi
.ad b

.P
will generate an RSS file containing documents http://mysite.org/blog/post1.html and http://mysite.org/blog/post2.html.
.P
Sometimes you may wish to build an RSS for files that are not in the current directory. For this the "-b" (basename) option exists. e.g. if you have website files in /home/webmaster/blog you might generate an rss with:

.nf

	rssgen http://mysite.org/blog/ \-t "My Blog" \-b /home/webmaster/blog/*.html
.fi
.ad b
.P
And this will strip the leading path from the html files and generate an RSS file containing documents http://mysite.org/blog/post1.html and http://mysite.org/blog/post2.html. Without the "-b" flag the paths will be included, so final URLs will be http://mysite.org/blog/home/webmaster/blog/post1.html etc.

.SS META TAGS
.P
rssgen uses meta-tags within the document to get information about it. These are:

.nf

<meta name="title" content="Title for this document">
<meta name="description" content="Description of this document">
<meta name="author" content="author@somewhere.com">
<meta name="pubDate" content="Thu, 23 Nov 2016 20:43:16">
.fi
.ad b
.P
The "pubDate" meta-tag will also take dates in the following formats:

.nf

<meta name="pubDate" content="2016/11/23 20:43:16">
<meta name="pubDate" content="2016\-11\-23T20:43:16">
.fi
.ad b

.SS AUTHOR
.P
rssgen is copyright (C) 2016 Colum Paget. They are released under the GPL so you may do anything with them that the GPL allows.
.P
Email: colums.projects@gmail.com
